/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 body.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import { Texture } from "../../Utils/Types/Types";
import { Model3D } from "../../Utils/Interfaces/Interfaces";

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh;
    Arms: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export const Body: React.FC<Model3D>  = ({ texture }) => {
  const { nodes, materials } = useGLTF("Models/body.glb") as GLTFResult;
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Body.geometry} position={[0, -3.34, 0]}>
        <meshStandardMaterial map={useTexture(texture)} />
      </mesh>
      <mesh
        geometry={nodes.Arms.geometry}
        material={materials["Material.001"]}
        position={[0, -3.34, 0]}
      />
    </group>
  );
};

useGLTF.preload("Models/body.glb");
